/**
 * emoji-loader.ts -- fetches the gzipped emoji data at startup, decompresses,
 * parses the text format, and provides the emoji SVG lookup.
 *
 * The data file (emojis.txt.gz) is generated by scripts/emoji-gen.ts and copied
 * to dist/public/ by the build script. Format: one entry per line:
 *   <emoji_char>;<minified_svg_text>
 * Split on the FIRST semicolon only -- SVG content may contain semicolons.
 */

import { gunzipSync } from "fflate";

let EMOJI_SVGS: Record<string, string> | null = null;

/** Ensure the emoji data is loaded. Starts fetch on module init. */
const loadPromise = loadEmojiData();

async function loadEmojiData(): Promise<void> {
  try {
    const resp = await fetch("/emojis.txt.gz");
    if (!resp.ok) {
      console.error("Failed to load emoji data:", resp.status);
      return;
    }
    const compressed = new Uint8Array(await resp.arrayBuffer());
    const decompressed = gunzipSync(compressed);
    const text = new TextDecoder().decode(decompressed);

    const map: Record<string, string> = Object.create(null);
    for (const line of text.split("\n")) {
      if (line === "") continue;
      const semiIdx = line.indexOf(";");
      if (semiIdx < 0) continue;
      const emoji = line.slice(0, semiIdx);
      const svgText = line.slice(semiIdx + 1);
      map[emoji] = svgText;
    }
    EMOJI_SVGS = map;
  } catch (err) {
    console.error("Failed to load/decompress emoji data:", err);
  }
}

/**
 * Get the SVG text for an emoji character.
 * Returns undefined if the data hasn't loaded yet or the emoji isn't found.
 */
export function getEmojiSvg(native: string): string | undefined {
  return EMOJI_SVGS?.[native];
}

/** True once emoji data has been loaded and parsed. */
export function isEmojiDataLoaded(): boolean {
  return EMOJI_SVGS !== null;
}

/** Wait for emoji data to be loaded. Useful for the picker or eager init. */
export function waitForEmojiData(): Promise<void> {
  return loadPromise;
}

// Kick off the fetch immediately on module import
void loadPromise;
